theme = "revontuli_night_transparent"

[editor]
line-number = "relative"
scroll-lines = 3
bufferline = "multiple"
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]

C-r = "redo"

x = "extend_line"

# Vim
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

0 = "goto_first_nonwhitespace"
"^" = "goto_line_start"
"$" = "goto_line_end"

u = ["undo", "collapse_selection"]

G = "goto_last_line"

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

";" = ["collapse_selection", "normal_mode"]

x = "extend_line"

# Vim
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

i = "select_textobject_inner"
a = "select_textobject_around"

0 = "goto_first_nonwhitespace"
"^" = "goto_line_start"
"$" = "goto_line_end"

G = "goto_last_line"
